name: Pull Request CI
on:
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 16

jobs:
  ci:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm ci

      - name: Run linters
        if: always()
        run: npm run lint

      - name: Check types
        if: always()
        run: npm run typecheck

      - name: Run tests
        if: always()
        run: npm test
