name: Pull Request CI
on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install packages
        run: |
          pnpm --version
          pnpm install

      - name: Run linters
        if: always()
        run: pnpm run lint

      - name: Check types
        if: always()
        run: pnpm run typecheck

      - name: Run tests
        if: always()
        run: pnpm test
