name: Update Reviews
on:
  workflow_dispatch: {}
  schedule:
    - cron: '00 16 * * 0'

env:
  DATABASE_URL: "file:./dev.db"

jobs:
  UpdateDatabase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: bahmutov/npm-install@v1

      - name: 'Pull Pitchfork Best New Music reviews'
        run: npm run seed-script -- prisma/seed-scripts/pitchfork.ts --slug bnm

      - name: 'Pull Pitchfork Best New Reissue reviews'
        run: npm run seed-script -- prisma/seed-scripts/pitchfork.ts --slug bnr

      - name: 'Pull Pitchfork Sunday Reviews'
        run: npm run seed-script -- prisma/seed-scripts/pitchfork.ts --slug sunday-reviews

      - name: 'Pull Pitchfork 8.0+ reviews'
        run: npm run seed-script -- prisma/seed-scripts/pitchfork.ts --slug 8-plus

      - name: 'Pull Pitchfork 7.0+ reviews'
        run: npm run seed-script -- prisma/seed-scripts/pitchfork.ts --slug 7-plus

      - name: 'Pull Bandcamp Daily reviews'
        run: npm run seed-script -- prisma/seed-scripts/bandcamp-daily.ts

      - name: 'Commit changes, if needed'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Automated database update from GitHub Actions'
          commit_user_name: 'DJ Octo[bot]'
          commit_user_email: 'eligundry+dj.octobot@gmail.com'
          commit_author: 'DJ Octo[bot] <eligundry+dj.octobot@gmail.com>'
          file_pattern: 'prisma/dev.db'
